version: '3.9'

services:
  sky_service_db:
    image: mariadb10.5
    container_name: sky_db
    ports:
      - "4306:3306"
    volumes:
      - ./db-data/:/var/lib/mysql
      - ./docker/config/mariadb/custom.cnf:/etc/mysql/mariadb.conf.d/custom.cnf
      - ./docker/config/dbdata:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sky
      MYSQL_PASSWORD: sky
      MYSQL_DATABASE: sky
      TZ: Asia/Seoul
    #restart: always
    networks:
      - sky_service_net

networks:
  sky_service_net:
    driver: bridge

# docker-compose -f docker-compose.local.yml up
# docker-compose -f docker-compose.local.yml down
