server:
  port: 9092
  forward-headers-strategy: framework

spring:
  application:
    name: spring-server
  datasource:   #데이터베이스 정보 추가
    url: jdbc:mariadb://localhost:4306/sky
    driverClassName: org.mariadb.jdbc.Driver
    username: sky
    password: sky

    hikari:
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 30000
      validation-timeout: 5000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        query:
          in_clause_parameter_padding : true
        format_sql: true  #sql을 포멧팅해서 예쁘게 로그 보여줌
        show_sql: true  #프로젝트 실행 시 sql문을 로그로 보여줌
    hibernate:
      ddl-auto: none #자동으로 DDL(Create, Update)하는 것 / create, update, none
    open-in-view: false
    database-platform: org.hibernate.dialect.MariaDB10Dialect
  #    defer-datasource-initialization: true
  sql:
    init:
      mode: always

logging:
  level:
    root: info
    org:
      springframework:
        boot:
          autoconfigure: INFO # 구동시 class matched 연결 결과 debug 용
        core:
          LocalVariableTableParameterNameDiscoverer: error
      hibernate:
        orm:
          jdbc:
            bind: trace


